import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main>
          <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex exercitationem, hic laborum nihil officia
              officiis possimus tempora. Adipisci, aperiam autem enim esse, explicabo fugiat id inventore ipsa, nesciunt
              tempora voluptatibus.
          </div>
          <div>Ad esse iure magnam quisquam sit. Accusamus aut delectus eligendi expedita incidunt libero minima
              necessitatibus, perspiciatis placeat quasi? Aliquam debitis impedit numquam quibusdam veritatis? A cumque
              dolores laborum numquam placeat.
          </div>
          <div>Animi aspernatur est nisi nobis unde. Accusamus, accusantium, adipisci animi aut consequatur dolor
              doloribus eaque earum eligendi inventore iste magni maxime nisi nobis officia porro quas quia rem tenetur
              ut?
          </div>
          <div>Alias eos excepturi hic nemo provident quis suscipit veritatis! Ad amet aperiam autem, consequatur, cum
              dolores exercitationem fugit minima odio omnis porro quas totam vitae voluptas voluptatum. Distinctio
              odio, voluptatibus.
          </div>
          <div>Consequatur corporis cum delectus distinctio doloribus eaque excepturi, explicabo fuga harum hic iste
              maiores minus molestiae officia omnis quasi qui quia quidem ratione recusandae repellat tempore unde velit
              veniam, voluptatum.
          </div>
          <div>Ab atque autem distinctio doloremque dolores ea eius exercitationem fugit illo inventore ipsum magnam
              molestias, neque nihil nobis officia quae qui reprehenderit sit sunt suscipit ullam voluptas voluptatum.
              Atque, deleniti!
          </div>
          <div>Amet autem, dignissimos, eius expedita facere inventore mollitia nostrum quis quos reiciendis similique
              vero, vitae? Aut consectetur culpa error id iusto nam nulla, quidem vero. Fugit non possimus saepe ullam!
          </div>
          <div>Accusamus, aliquid aspernatur deleniti dolor dolorem dolores eveniet, exercitationem hic impedit ipsum
              labore mollitia natus porro quia quo quod totam, velit veritatis vitae voluptatem! Ea id omnis velit
              voluptatem voluptatum!
          </div>
          <div>Ipsum, nisi nulla. Aut delectus, ipsa minima molestiae numquam pariatur praesentium saepe? A aliquam
              animi aspernatur dicta distinctio dolorem excepturi expedita fugiat ipsa, minus odio possimus quasi
              recusandae. Aut, nemo?
          </div>
          <div>Aut autem cumque deleniti distinctio eveniet laudantium minima necessitatibus, quae quo reprehenderit. A
              accusamus accusantium animi cupiditate, doloremque eaque est laboriosam, maiores minus molestiae obcaecati
              quia quo quod reiciendis voluptates.
          </div>
      </main>
    </>
  )
}
